# Generated by Django 4.1.5 on 2025-07-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
